### PR TITLE
implementing remaining slot booking TODOs

### PR DESCRIPTION
**Pull request by RiedleroD**
all the important stuff to finish the slot booking service

### CODE REVIEW

**Comment by RiedleroD** [comment]
The slots subpackage should now be complete in terms of services to implement. I think we should merge this before fixing the remaining three issues, because:
- #16 is not in slots subpackage, so it's out of scope for this PR
- #17 needs large refactors, so I'd like to have it in its own PR to not clutter this one
- #28 needs large refactors, as well as communication with the front-end team

**Comment by RiedleroD** [comment]
@mcquenji please check if there's any problems wrt API structure. Obviously you don't need to look at the exact implementations. You can read the docs by copying the array from the CI results and putting it into the scrips.js of your local copy of the docs website thingy.

**Comment by mcquenji** [comment]
image

id dont quite understand what this is used for, as they arent used as a parameter in any other endpoint (maybe im missing something?)

rest looks good

**Comment by mcquenji** [comment]
oh my bad, are they used to limit who can book a slot? if so, maybe rename them to access_rule or something?

**Comment by RiedleroD** [comment]
yes, I was thinking of renaming them. We can discuss names for this tomorrow

**Comment by RiedleroD** [comment]
slot filter renamed: whitelist (or whitelist_rule for the individual elements making up the whitelist)

**Review by mcquenji — APPROVED** [review]

**Comment by RiedleroD** [comment]
gonna actually rename everything in a separate PR so I can get this merged sooner rather than later

**Pull request merged**
